jdk1.7 如果本地变量用于内部类中需要定义为 final 类型
src/main/java/org/gaixie/jibu/mail/JavaMailSender.java:50:
error: local variable usr is accessed from within inner class;
needs to be declared final
    return new PasswordAuthentication(usr,pwd);

http://stackoverflow.com/questions/3013547/about-local-final-variables-in-java